# Generated by Django 4.0.4 on 2022-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthClients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
